spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true

application:
  title: seonwoo's blog
  banner:
    title: welcome to seonwoo's blog
    content: this is the content